# required metadata
sonar.projectKey=plt-server
sonar.projectName=PLT Server
sonar.projectVersion=0.21.9-SNAPSHOT
 
# optional description
sonar.projectDescription=Project PLT.
 
# path to source directories (required)
sonar.sources=./src

# test
sonar.tests=./src
sonar.test.inclusions=src/**/*.spec.js,src/**/*.spec.ts

sonar.exclusions=src/main.ts,src/app.module.ts,src/seeder.module.ts,src/seeder.ts,src/**/*.seeder.ts
 
# The value of the property must be the key of the language.
sonar.language=js
 
# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Coverage test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
